#!/usr/bin/env python3
import os

workingdir = "/tmp/"
os.system("cd %s" % workingdir)
os.system("wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install-papirus-root.sh | sh")
